name: example_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  thermion_dart: 
    git:
      url: git@github.com:nmfisher/thermion_windows_fix.git
      path: thermion_dart
dependency_overrides:
  native_toolchain_c:
    git:
      url: https://github.com/nmfisher/native.git
      path: pkgs/native_toolchain_c
      ref: windows_dll_fix
dev_dependencies:
  ffigen: ^11.0.0
  lints: ^3.0.0
  test: ^1.24.0
