name: example_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  thermion_dart: 0.1.1+2

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^3.0.0
  test: ^1.24.0
